---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: devops-kube-audit
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  tail:
    tag: devops-kube-audit.*
    path: /var/log/kubernetes/audit.log
    refreshIntervalSeconds: 10
    memBufLimit: 500MB
    db: /fluent-bit/devops-kube-audit.db
    dbSync: Normal

---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: devops-kube-audit
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  match: devops-kube-audit.*
  filters:
    - parser:
        keyName: log
        parser: json

    - recordModifier:
        records:
          - clusterName demo1

    - modify:
        rules:
          - rename: {"requestReceivedTimestamp": "@timestamp"}
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: devops-kube-audit
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  matchRegex: devops-kube-audit.*
  es:
    host: 172.16.100.10
    index: devops-kube-audit-%Y.%m.%d
    port: 9200
    replaceDots: true
    suppressTypeName: "false"
    traceError: true
    type: _doc
    timeKey: "@timestamp"
  
