---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: devops-kube-system
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  systemd:
    tag: devops-kube-system.*
    path: /var/log/journal
    db: /fluent-bit/devops-kube-system.db
    dbSync: Normal
    systemdFilter:
      - _SYSTEMD_UNIT=kube-apiserver.service
      - _SYSTEMD_UNIT=kube-scheduler.service
      - _SYSTEMD_UNIT=kube-controller-manager.service
      - _SYSTEMD_UNIT=kube-proxy.service
      - _SYSTEMD_UNIT=kubelet.service
      - _SYSTEMD_UNIT=etcd.service
      - _SYSTEMD_UNIT=crio.service
      - _SYSTEMD_UNIT=docker.service
      - _SYSTEMD_UNIT=containerd.service
      - _SYSTEMD_UNIT=haproxy.service
      - _SYSTEMD_UNIT=keepalived.service

---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: devops-kube-system
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  match: devops-kube-system.*
  filters:

    - parser:
        reserveData: true
        keyName: MESSAGE
        parser: json

    - modify:
        rules:
          - rename: {"ts": "@timestamp"}
          - rename: {"msg": "message"}

---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: devops-kube-system
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  matchRegex: devops_kube_system.*
  es:
    host: 172.16.0.146
    port: 9200
    logstashPrefix: devops_kube_system
    logstashFormat: true

