---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterInput
metadata:
  name: devops-kube-system
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  systemd:
    tag: devops-kube-system.*
    path: /var/log/journal
    db: /fluent-bit/devops-kube-system.db
    dbSync: Normal
    systemdFilter:
      - _SYSTEMD_UNIT=kube-apiserver.service
      - _SYSTEMD_UNIT=kube-scheduler.service
      - _SYSTEMD_UNIT=kube-controller-manager.service
      - _SYSTEMD_UNIT=kube-proxy.service
      - _SYSTEMD_UNIT=kubelet.service
      - _SYSTEMD_UNIT=etcd.service
      - _SYSTEMD_UNIT=crio.service
      - _SYSTEMD_UNIT=docker.service
      - _SYSTEMD_UNIT=containerd.service
      - _SYSTEMD_UNIT=haproxy.service
      - _SYSTEMD_UNIT=keepalived.service

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: devops-kube-system
data:
  systemd.lua: |
    function add_time(tag, timestamp, record)
      new_record = {}

      timeStr = os.date("!*t", timestamp["sec"])
      t = string.format("%4d-%02d-%02dT%02d:%02d:%02d.%sZ",
      timeStr["year"], timeStr["month"], timeStr["day"],
      timeStr["hour"], timeStr["min"], timeStr["sec"],
      timestamp["nsec"])

      new_record["@timestamp"] = t
      new_record["log"] = record["MESSAGE"]

      return 1, timestamp, new_record
    end
    
---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterFilter
metadata:
  name: devops-kube-system
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  match: devops-kube-system.*
  filters:
    - lua:
        script:
          key: systemd.lua
          name: devops-kube-system
        call: add_time
        timeAsTable: true

    - parser:
        reserveData: true
        keyName: log
        parser: json

---
apiVersion: fluentbit.fluent.io/v1alpha2
kind: ClusterOutput
metadata:
  name: devops-kube-system
  labels:
    fluentbit.fluent.io/infra: "true"
spec:
  matchRegex: devops-kube-system.*
  es:
    host: 172.16.0.146
    port: 9200
    logstashPrefix: devops_kube_system
    logstashFormat: true

