apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFluentdConfig
metadata:
  name: demo1-noprod
  labels:
    config.fluentd.fluent.io/enabled: "true"
spec:
  watchedNamespaces:
    - demo1-dev
    - demo1-uat
  clusterOutputSelector:
    matchLabels:
      output.fluentd.fluent.io/enabled: "true"
      output.fluentd.fluent.io/scope: "demo1-noprod"

---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: demo1-noprod
  labels:
    output.fluentd.fluent.io/enabled: "true"
    output.fluentd.fluent.io/scope: "demo1-noprod"
spec:
  outputs:
    - elasticsearch:
        host: 172.16.3.13
        port: 9200
        logstashFormat: true
        logstashPrefix: demo1-noprod
 
---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterFluentdConfig
metadata:
  name: demo1-prod
  labels:
    config.fluentd.fluent.io/enabled: "true"
spec:
  watchedNamespaces:
    - demo1-prod
  clusterOutputSelector:
    matchLabels:
      output.fluentd.fluent.io/enabled: "true"
      output.fluentd.fluent.io/scope: "demo1-prod"

---
apiVersion: fluentd.fluent.io/v1alpha1
kind: ClusterOutput
metadata:
  name: demo1-prod
  labels:
    output.fluentd.fluent.io/enabled: "true"
    output.fluentd.fluent.io/scope: "demo1-prod"
spec:
  outputs:
    - elasticsearch:
        host: 172.16.3.13
        port: 9200
        logstashFormat: true
        logstashPrefix: demo1-prod